{{- if .Values.sftp.secret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "dvsmart-destination-filesystem-sftp.fullname" . }}-sftp-secret
  labels:
    {{- include "dvsmart-destination-filesystem-sftp.labels" . | nindent 4 }}
type: Opaque
stringData:
  SFTP_USERS: {{ .Values.sftp.secret.sftpUsers | quote }}
{{- end }}