{{- if .Values.volume.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ printf "%s-pvc" (include "dvsmart-batch-postgresql.fullname" .) }}
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.volume.storage }}
  storageClassName: {{ .Values.volume.storageClass }}
{{- end }}