apiVersion: v1
kind: Service
metadata:
  name: {{ include "dvsmart-postgresql.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "dvsmart-postgresql.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: tcp
      port: {{ .Values.service.port }}
      protocol: TCP
      targetPort: {{ .Values.service.port }}      
  selector:
    {{- include "dvsmart-postgresql.selectorLabels" . | nindent 4 }}
