#################################################################
# Enable/disable helm charts
# to customize the SROM deployment.
#################################################################
dvsmart-destination-filesystem-sftp:
  enabled: true
dvsmart-source-filesystem-sftp:
  enabled: true
dvsmart-catalog-mongodb:
  enabled: true
dvsmart-reorganization-api:
  enabled: true
global:
  env: loc
  tag: ""